### ISSUE TITLE
No CSV download button in 2023

### ISSUE THREAD

**Issue by tanhoaian01** [LucunJi/brainscape-bene#1]
### Description
I don't see any csv download button for this [official Mandarin deck](https://www.brainscape.com/l/dashboard/chinese-mandarin-1028/decks), despite updating the script to match the required url. Can you kindly update the code? Does this script include scraping audios? Thank you in advance.

![image](https://github.com/LucunJi/brainscape-bene/assets/133650669/1d15bc45-21cc-4365-9175-80aa9388a220)

**Comment by LucunJi** [comment]
Currently, people can import/export decks from/to Brainscape with a free account.

More importantly, **_downloading a deck that you do not own has legal issues_**, so it is never an intended feature of this script.
